specVersion: 1.0.0
name: phala-world-subquery
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: Phala World Indexer for SubQuery
repository: 'https://github.com/Phala-Network/phala-world-subquery.git'
schema:
  file: ./schema.graphql
network:
  chainId: '0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d'
  endpoint: 'wss://khala.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/khala-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1938472
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMintedOriginOfShell
          kind: substrate/EventHandler
          filter:
            module: PWNftSale
            method: OriginOfShellMinted
        - handler: handleStartedIncubation
          kind: substrate/EventHandler
          filter:
            module: PWIncubation
            method: StartedIncubation
        - handler: handleMintedShell
          kind: substrate/EventHandler
          filter:
            module: PWIncubation
            method: ShellAwakened
        - handler: handleNftListed
          kind: substrate/EventHandler
          filter:
            module: RmrkMarket
            method: TokenListed
        - handler: handleNftUnlisted
          kind: substrate/EventHandler
          filter:
            module: RmrkMarket
            method: TokenUnlisted
        - handler: handleNftSold
          kind: substrate/EventHandler
          filter:
            module: RmrkMarket
            method: TokenSold
